name: Sync to GitLab

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:glpat-QEiyWJSKklTFC4VgXY7bIGM6MQpvOjEKdTpiMzBnaQ8.01.170p8dyqp@gitlab.com/daniele.valentini1972/comp_target.git
          git push --force gitlab HEAD:main --tags
