
name: Sync to GitLab

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Push to GitLab
        run: |
          if [ -z "${{ secrets.GITLAB_TOKEN }}" ]; then
            echo "TOKEN MANCANTE"
          else
            echo "TOKEN PRESENTE"
          fi
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/daniele.valentini1972/comp_target.git
          git push --force --mirror gitlab
          
      
